# Generated by Django 4.2 on 2023-04-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='city',
        ),
    ]
