# Generated by Django 4.2 on 2023-04-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sweden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('region', models.CharField(max_length=50)),
            ],
        ),
    ]
