# Generated by Django 4.2 on 2023-04-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweden', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sweden',
            new_name='SwedenCity',
        ),
    ]
