# Generated by Django 4.2 on 2023-04-14 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweden', '0003_city_delete_swedencity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='region',
        ),
    ]
