# Generated by Django 4.2 on 2023-04-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_remove_region_city'),
        ('sweden', '0004_remove_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='regions.region'),
            preserve_default=False,
        ),
    ]
