# Generated by Django 4.2 on 2023-04-14 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('must_see', '0002_remove_mustsee_in_cities'),
        ('sweden', '0005_city_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='musts',
            field=models.ManyToManyField(related_name='must_sees', to='must_see.mustsee'),
        ),
    ]
