# Generated by Django 4.2 on 2023-04-14 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sweden', '0006_city_musts'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='city', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
