# Generated by Django 4.2 on 2023-04-15 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweden', '0007_city_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.URLField(default=1, validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
