# Generated by Django 4.2 on 2023-04-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attraction',
            name='long',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
