# Generated by Django 4.2 on 2023-04-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sweden', '0005_city_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='MustSee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('in_cities', models.ManyToManyField(related_name='must_sees', to='sweden.city')),
            ],
        ),
    ]
