# Generated by Django 4.2 on 2023-04-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('must_see', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustsee',
            name='in_cities',
        ),
    ]
