# Generated by Django 4.2 on 2023-04-14 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('must_see', '0002_remove_mustsee_in_cities'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustsee',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='musts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
